[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
    name = "88_Merge_Sorted_Array"
    path = "src/main.rs"

[dependencies]

